### ISSUE TITLE
Cannot connect to the DB

### ISSUE THREAD

**Issue by rodloboz** [germsvel/watwitter#1]
Hi I've got Postgresql runnin on MacOS with homebrew, but when I follow your setup instructions `mix ecto.setup` it cannot connect to the database:

```
17:28:53.061 [error] GenServer #PID<0.520.0> terminating
** (DBConnection.ConnectionError) tcp connect (localhost:5432): connection refused - :econnrefused
    (db_connection 2.3.0) lib/db_connection/connection.ex:99: DBConnection.Connection.connect/2
    (connection 1.0.4) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib 3.14) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol
** (Mix) The database for Watwitter.Repo couldn't be created: killed
```

**Comment by germsvel** [comment]
Hey @rodloboz , were you able to get this sorted out?

**Comment by rodloboz** [comment]
Hi @germsvel, yes, it was completely unrelated to this repo. I did something before cloning it that messed up my postgresql locally.
